/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TRANGCHU;
import BackupRestore.BackupRestore;
import ChonKM.PnKM;
import ChonSach.PnSach;
import ChonSach.SachFrame;
import DANGNHAP.DangNhap;
import KMForm.KMForm;
import DANGNHAP.TAIKHOAN;
import java.awt.Color; 
/**
 *
 * @author hoang
 */
import HOADON.HOADON;
import ThongTinTK.ThongTin;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class FTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form FTrangChu
     */
    TAIKHOAN tk;
    public JPanel jpnView2;
    public TAIKHOAN getTK(){
        return tk;
    }
    public FTrangChu() {
        initComponents();
    }
    public JPanel getjpnView(){
        return jpnView2;
    }
    public FTrangChu(TAIKHOAN in_tk) {
        initComponents();
        tk = in_tk;
        jpnView2 = jpnview;
    }
    
    public void LamMoi(){
        jpnCN.setBackground(new Color(0, 102, 102));
        jpnSach.setBackground(new Color(0, 102, 102));
        jpnHD.setBackground(new Color(0, 102, 102));
        jpnKM.setBackground(new Color(0, 102, 102));
        jpnKhac.setBackground(new Color(0, 102, 102));
        jpnTT.setBackground(new Color(0, 102, 102));
        jpnburs.setBackground(new Color(0, 102, 102));
        jlbCN.setBackground(new Color(0, 102, 102));
        jlbSach.setBackground(new Color(0, 102, 102));
        jlbHD.setBackground(new Color(0, 102, 102));
        jlbKM.setBackground(new Color(0, 102, 102));
        jlbKhac.setBackground(new Color(0, 102, 102));
        jlbTT.setBackground(new Color(0, 102, 102));
        jlbburs.setBackground(new Color(0, 102, 102));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnroot = new javax.swing.JPanel();
        panelBoderFrm1 = new PanelBoder.PanelBoderFrm();
        jpnTT = new javax.swing.JPanel();
        jlbTT = new javax.swing.JLabel();
        jpnCN = new javax.swing.JPanel();
        jlbCN = new javax.swing.JLabel();
        jpnSach = new javax.swing.JPanel();
        jlbSach = new javax.swing.JLabel();
        jpnHD = new javax.swing.JPanel();
        jlbHD = new javax.swing.JLabel();
        jpnKM = new javax.swing.JPanel();
        jlbKM = new javax.swing.JLabel();
        jpnKhac = new javax.swing.JPanel();
        jlbKhac = new javax.swing.JLabel();
        jpnDXuat = new javax.swing.JPanel();
        jlbDXuat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpnburs = new javax.swing.JPanel();
        jlbburs = new javax.swing.JLabel();
        jpnview = new PanelBoder.PanelBoderFrm();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelBoderFrm2 = new PanelBoder.PanelBoderFrm();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);

        jpnroot.setBackground(new java.awt.Color(0, 51, 102));

        panelBoderFrm1.setBackground(new java.awt.Color(253, 240, 205));

        jpnTT.setBackground(new java.awt.Color(0, 51, 102));
        jpnTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnTTMouseClicked(evt);
            }
        });

        jlbTT.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlbTT.setForeground(new java.awt.Color(255, 255, 255));
        jlbTT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jlbTT.setText("    TRANG CHỦ");

        javax.swing.GroupLayout jpnTTLayout = new javax.swing.GroupLayout(jpnTT);
        jpnTT.setLayout(jpnTTLayout);
        jpnTTLayout.setHorizontalGroup(
            jpnTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTTLayout.setVerticalGroup(
            jpnTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTTLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbTT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jpnCN.setBackground(new java.awt.Color(0, 51, 102));
        jpnCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnCNMouseClicked(evt);
            }
        });

        jlbCN.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlbCN.setForeground(new java.awt.Color(255, 255, 255));
        jlbCN.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jlbCN.setText("    CÁ NHÂN");
        jlbCN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpnCNLayout = new javax.swing.GroupLayout(jpnCN);
        jpnCN.setLayout(jpnCNLayout);
        jpnCNLayout.setHorizontalGroup(
            jpnCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnCNLayout.setVerticalGroup(
            jpnCNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCNLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbCN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnSach.setBackground(new java.awt.Color(0, 51, 102));
        jpnSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnSachMouseClicked(evt);
            }
        });

        jlbSach.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlbSach.setForeground(new java.awt.Color(255, 255, 255));
        jlbSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book-of-black-cover-closed.png"))); // NOI18N
        jlbSach.setText("        SÁCH");
        jlbSach.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpnSachLayout = new javax.swing.GroupLayout(jpnSach);
        jpnSach.setLayout(jpnSachLayout);
        jpnSachLayout.setHorizontalGroup(
            jpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnSachLayout.setVerticalGroup(
            jpnSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSachLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnHD.setBackground(new java.awt.Color(0, 51, 102));
        jpnHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnHDMouseClicked(evt);
            }
        });

        jlbHD.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlbHD.setForeground(new java.awt.Color(255, 255, 255));
        jlbHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice (1).png"))); // NOI18N
        jlbHD.setText("    HÓA ĐƠN");
        jlbHD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpnHDLayout = new javax.swing.GroupLayout(jpnHD);
        jpnHD.setLayout(jpnHDLayout);
        jpnHDLayout.setHorizontalGroup(
            jpnHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnHDLayout.setVerticalGroup(
            jpnHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHDLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnKM.setBackground(new java.awt.Color(0, 51, 102));
        jpnKM.setForeground(new java.awt.Color(255, 255, 255));
        jpnKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnKMMouseClicked(evt);
            }
        });

        jlbKM.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlbKM.setForeground(new java.awt.Color(255, 255, 255));
        jlbKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shopping-bag.png"))); // NOI18N
        jlbKM.setText("  KHUYẾN MÃI");
        jlbKM.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpnKMLayout = new javax.swing.GroupLayout(jpnKM);
        jpnKM.setLayout(jpnKMLayout);
        jpnKMLayout.setHorizontalGroup(
            jpnKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnKMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnKMLayout.setVerticalGroup(
            jpnKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKMLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbKM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnKhac.setBackground(new java.awt.Color(0, 51, 102));
        jpnKhac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnKhacMouseClicked(evt);
            }
        });

        jlbKhac.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlbKhac.setForeground(new java.awt.Color(255, 255, 255));
        jlbKhac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manager.png"))); // NOI18N
        jlbKhac.setText("    QUẢN LÝ");
        jlbKhac.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpnKhacLayout = new javax.swing.GroupLayout(jpnKhac);
        jpnKhac.setLayout(jpnKhacLayout);
        jpnKhacLayout.setHorizontalGroup(
            jpnKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnKhacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbKhac, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnKhacLayout.setVerticalGroup(
            jpnKhacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhacLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnDXuat.setBackground(new java.awt.Color(0, 51, 102));
        jpnDXuat.setForeground(new java.awt.Color(255, 255, 255));
        jpnDXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnDXuatMouseClicked(evt);
            }
        });

        jlbDXuat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlbDXuat.setForeground(new java.awt.Color(255, 255, 255));
        jlbDXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jlbDXuat.setText("     EXIT");
        jlbDXuat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpnDXuatLayout = new javax.swing.GroupLayout(jpnDXuat);
        jpnDXuat.setLayout(jpnDXuatLayout);
        jpnDXuatLayout.setHorizontalGroup(
            jpnDXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDXuatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbDXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnDXuatLayout.setVerticalGroup(
            jpnDXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDXuatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbDXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/open-book.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jpnburs.setBackground(new java.awt.Color(0, 51, 102));
        jpnburs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnbursMouseClicked(evt);
            }
        });

        jlbburs.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlbburs.setForeground(new java.awt.Color(255, 255, 255));
        jlbburs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manager.png"))); // NOI18N
        jlbburs.setText("Backup & Restore");
        jlbburs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jpnbursLayout = new javax.swing.GroupLayout(jpnburs);
        jpnburs.setLayout(jpnbursLayout);
        jpnbursLayout.setHorizontalGroup(
            jpnbursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnbursLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbburs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnbursLayout.setVerticalGroup(
            jpnbursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnbursLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbburs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBoderFrm1Layout = new javax.swing.GroupLayout(panelBoderFrm1);
        panelBoderFrm1.setLayout(panelBoderFrm1Layout);
        panelBoderFrm1Layout.setHorizontalGroup(
            panelBoderFrm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(panelBoderFrm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBoderFrm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnCN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnKhac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoderFrm1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnDXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(panelBoderFrm1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnburs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBoderFrm1Layout.setVerticalGroup(
            panelBoderFrm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jpnTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKhac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnburs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnDXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jpnview.setBackground(new java.awt.Color(253, 240, 205));

        jScrollPane1.setBackground(new java.awt.Color(235, 212, 155));
        jScrollPane1.setBorder(null);

        panelBoderFrm2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bìa/Nền.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bìa/Thiết kế chưa có tên (1).jpg"))); // NOI18N

        javax.swing.GroupLayout panelBoderFrm2Layout = new javax.swing.GroupLayout(panelBoderFrm2);
        panelBoderFrm2.setLayout(panelBoderFrm2Layout);
        panelBoderFrm2Layout.setHorizontalGroup(
            panelBoderFrm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm2Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBoderFrm2Layout.setVerticalGroup(
            panelBoderFrm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoderFrm2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(panelBoderFrm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelBoderFrm2);

        javax.swing.GroupLayout jpnviewLayout = new javax.swing.GroupLayout(jpnview);
        jpnview.setLayout(jpnviewLayout);
        jpnviewLayout.setHorizontalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jpnviewLayout.setVerticalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnrootLayout = new javax.swing.GroupLayout(jpnroot);
        jpnroot.setLayout(jpnrootLayout);
        jpnrootLayout.setHorizontalGroup(
            jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnrootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBoderFrm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnrootLayout.setVerticalGroup(
            jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnrootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBoderFrm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpnroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnroot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpnCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnCNMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnCN.setBackground(new Color(96, 100, 191));
        jlbCN.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new ThongTin(tk));
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnCNMouseClicked

    private void jpnSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnSachMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnSach.setBackground(new Color(96, 100, 191));
        jlbSach.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new PnSach());
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnSachMouseClicked

    private void jpnHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHDMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnHD.setBackground(new Color(96, 100, 191));
        jlbHD.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new HOADON(tk).getJPN());
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnHDMouseClicked

    private void jpnKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnKMMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnKM.setBackground(new Color(96, 100, 191));
        jlbKM.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new PnKM());
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnKMMouseClicked

    private void jpnKhacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnKhacMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnKhac.setBackground(new Color(96, 100, 191));
        jlbKhac.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new FChucNangKhac(tk));
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnKhacMouseClicked

    private void jpnDXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDXuatMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,"Bạn có muốn đăng xuất không?","xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION){
            new DangNhap().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jpnDXuatMouseClicked

    private void jpnTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTTMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnTT.setBackground(new Color(96, 100, 191));
        jlbTT.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());
        jpnview.add(new FTrangChu(tk).getjpnView());
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnTTMouseClicked

    private void jpnbursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnbursMouseClicked
        // TODO add your handling code here:
        LamMoi();
        jpnburs.setBackground(new Color(96, 100, 191));
        jlbburs.setBackground(new Color(96, 100, 191));
        jpnview.removeAll();
        jpnview.setLayout(new BorderLayout());  
        jpnview.add(new FTrangChu(tk).getjpnView());
        jpnview.validate();
        jpnview.repaint();
    }//GEN-LAST:event_jpnbursMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbCN;
    private javax.swing.JLabel jlbDXuat;
    private javax.swing.JLabel jlbHD;
    private javax.swing.JLabel jlbKM;
    private javax.swing.JLabel jlbKhac;
    private javax.swing.JLabel jlbSach;
    private javax.swing.JLabel jlbTT;
    private javax.swing.JLabel jlbburs;
    private javax.swing.JPanel jpnCN;
    private javax.swing.JPanel jpnDXuat;
    private javax.swing.JPanel jpnHD;
    private javax.swing.JPanel jpnKM;
    private javax.swing.JPanel jpnKhac;
    private javax.swing.JPanel jpnSach;
    private javax.swing.JPanel jpnTT;
    private javax.swing.JPanel jpnburs;
    private javax.swing.JPanel jpnroot;
    private PanelBoder.PanelBoderFrm jpnview;
    private PanelBoder.PanelBoderFrm panelBoderFrm1;
    private PanelBoder.PanelBoderFrm panelBoderFrm2;
    // End of variables declaration//GEN-END:variables
}
